# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: train
data_path: /home/harshmuriki/Documents/habitat-lab/data/datasets/replica_cad/rearrange/v2/{split}/rearrange_easy.json.gz
scenes_dir: "/home/harshmuriki/Documents/habitat-lab/data/replica_cad/"
